// SPDX-License-Identifier: Apache-2.0
// The builder compiler turns a BuilderGraph into a VALID, self-contained rego module: default triple
// always present, every OR-row a partial-set entry sharing its rule's rule_id, the verbatim resolver
// appended unconditionally, no data.*/forbidden-builtin references (nodes have no free-form rego).
// These assert the generated source is deterministic, round-trips its embedded graph blob, respects
// the same 65536-byte / 500-line / 25-regex-op caps the backend's `validate_rego_source` enforces,
// and rejects every malformed-graph shape at compile time (empty rule_id/reason, duplicate rule_id,
// zero conditions, empty keyword/tool list, out-of-range threshold, budget overrun) rather than
// emitting broken/dead rego. The live OPA decision-flip is proven manually (opa check --v0-compatible
// + opa eval against this exact fixture, see the round-A execution report) — a passing compile is not
// proof on its own, same doctrine as the rest of this repo's e2e checks.
import { describe, it, expect } from "vitest";
import { compileGraph, extractEmbeddedGraph, detachmentStatusOf, loaderKeyFor, scopeIdentifier, BUDGET_MAX_LINES } from "./builderCompile";
import type { BuilderGraph, BuilderRule, BuilderScope } from "./builderGraph";

function graphWith(rules: BuilderRule[], defaults: BuilderGraph["defaults"] = { decision: "allow", reason: "d" }): BuilderGraph {
  return { schemaVersion: 1, scope: { kind: "class", agentClass: "t" }, rules, defaults };
}

// The exact fixture graph from the round-A brief.
const FIXTURE_GRAPH: BuilderGraph = {
  schemaVersion: 1,
  scope: { kind: "class", agentClass: "spike-demo" },
  rules: [
    {
      id: "r1",
      decision: "block",
      ruleId: "builder_sql_block",
      reason: "SQL injection blocked by builder",
      conditions: [
        [{ type: "detector", detector: "sql_injection" }],
        [{ type: "keyword", keywords: ["drop table"], target: "params" }]
      ]
    }
  ],
  defaults: { decision: "allow", reason: "No builder rule matched" }
};

// Golden snapshot — the byte-for-byte compile of FIXTURE_GRAPH, verified against real OPA
// (`opa check --v0-compatible` + `opa eval`) during round-A execution.
const FIXTURE_GOLDEN_REGO = `package norviq.custom.spike_demo

# GENERATED by the Visual Policy Builder (graph -> rego compiler) for agent class "spike-demo".
# Source of truth is the GRAPH, embedded below as a base64 JSON blob; this rego is regenerated
# deterministically from it and is never hand-edited (see VISUAL-POLICY-BUILDER-PLAN.md, section 2).
# nrvq-builder-graph/v1: eyJzY2hlbWFWZXJzaW9uIjoxLCJzY29wZSI6eyJraW5kIjoiY2xhc3MiLCJhZ2VudENsYXNzIjoic3Bpa2UtZGVtbyJ9LCJydWxlcyI6W3siaWQiOiJyMSIsImRlY2lzaW9uIjoiYmxvY2siLCJydWxlSWQiOiJidWlsZGVyX3NxbF9ibG9jayIsInJlYXNvbiI6IlNRTCBpbmplY3Rpb24gYmxvY2tlZCBieSBidWlsZGVyIiwiY29uZGl0aW9ucyI6W1t7InR5cGUiOiJkZXRlY3RvciIsImRldGVjdG9yIjoic3FsX2luamVjdGlvbiJ9XSxbeyJ0eXBlIjoia2V5d29yZCIsImtleXdvcmRzIjpbImRyb3AgdGFibGUiXSwidGFyZ2V0IjoicGFyYW1zIn1dXX1dLCJkZWZhdWx0cyI6eyJkZWNpc2lvbiI6ImFsbG93IiwicmVhc29uIjoiTm8gYnVpbGRlciBydWxlIG1hdGNoZWQifX0=
# nrvq-builder-hash: f32a7f6d
default decision = "allow"
default rule_id = "builder_default_spike_demo"
default reason = "No builder rule matched"

bld_security_scan_texts[t] {
    walk(input.tool_params, [_, val])
    is_string(val)
    t := lower(val)
}
bld_security_scan_texts[t] {
    walk(input.tool_params_normalized, [_, val])
    is_string(val)
    t := lower(val)
}

bld_sql_patterns = ["drop table", "union select", "or '1'='1'", "or 1=1", "delete from", "xp_cmdshell", "exec ("]

bld_sql_destructive_patterns = ["drop table", "delete from", "truncate table", "; drop", "xp_cmdshell", "union select"]

bld_sql_syntax_context(val, pattern) { startswith(trim_space(val), pattern) }
bld_sql_syntax_context(val, _) { contains(val, ";") }

bld_kw_hit(text, terms) {
    is_string(text)
    term := terms[_]
    contains(lower(text), term)
}
bld_kw_hit_tool(terms) {
    bld_kw_hit(input.tool_name, terms)
}
bld_kw_hit_params(terms) {
    some bld_kw_p
    is_string(input.tool_params[bld_kw_p])
    bld_kw_hit(input.tool_params[bld_kw_p], terms)
}
bld_kw_hit_both(terms) {
    bld_kw_hit_tool(terms)
}
bld_kw_hit_both(terms) {
    bld_kw_hit_params(terms)
}

bld_sql_injection {
    input.tool_name == "execute_sql"
    query := bld_security_scan_texts[_]
    pattern := bld_sql_patterns[_]
    contains(query, pattern)
}
bld_sql_injection {
    val := bld_security_scan_texts[_]
    pattern := bld_sql_destructive_patterns[_]
    contains(val, pattern)
    bld_sql_syntax_context(val, pattern)
}

blocks["builder_sql_block"] {
    input.agent.agent_class == "spike-demo"
    bld_sql_injection
}
blocks["builder_sql_block"] {
    input.agent.agent_class == "spike-demo"
    bld_kw_hit_params(["drop table"])
}

escalates[id] { id := [][_] }

audits[id] { id := [][_] }

reasons = {
    "builder_sql_block": "SQL injection blocked by builder",
    "builder_default_spike_demo": "No builder rule matched",
}

block_fired { blocks[_] }
escalate_fired { escalates[_] }
audit_fired { audits[_] }
decision = "block" { block_fired }
decision = "escalate" { escalate_fired; not block_fired }
decision = "audit" { audit_fired; not block_fired; not escalate_fired }
rule_id = sort([id | blocks[id]])[0] { block_fired }
rule_id = sort([id | escalates[id]])[0] { escalate_fired; not block_fired }
rule_id = sort([id | audits[id]])[0] { audit_fired; not block_fired; not escalate_fired }
reason = reasons[rule_id]
`;

const TWO_RULE_GRAPH: BuilderGraph = graphWith(
  [
    {
      id: "r1",
      decision: "block",
      ruleId: "block_shell",
      reason: "Shell injection blocked",
      conditions: [[{ type: "detector", detector: "shell_injection" }]]
    },
    {
      id: "r2",
      decision: "escalate",
      ruleId: "low_trust",
      reason: "Trust too low",
      conditions: [[{ type: "trustBelow", threshold: 0.4 }]]
    }
  ],
  { decision: "allow", reason: "nothing matched" }
);

describe("builderCompile — golden snapshot", () => {
  it("compiles the round-A fixture graph to the exact pinned rego (verified against real OPA)", () => {
    const result = compileGraph(FIXTURE_GRAPH);
    expect(result.errors).toEqual([]);
    expect(result.rego).toBe(FIXTURE_GOLDEN_REGO);
  });
});

describe("builderCompile — shape", () => {
  it("a 2-rule graph compiles and contains the default triple, both partial-set entries, resolver lines", () => {
    const result = compileGraph(TWO_RULE_GRAPH);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain('default decision = "allow"');
    expect(result.rego).toContain('default rule_id = "builder_default_t"');
    expect(result.rego).toContain('default reason = "nothing matched"');
    expect(result.rego).toContain('blocks["block_shell"]');
    expect(result.rego).toContain('escalates["low_trust"]');
    expect(result.rego).toContain('input.agent.trust_score < 0.4');
    // resolver — the verbatim (adapted, no shell/sql shadow rule) template
    expect(result.rego).toContain("block_fired { blocks[_] }");
    expect(result.rego).toContain("escalate_fired { escalates[_] }");
    expect(result.rego).toContain("audit_fired { audits[_] }");
    expect(result.rego).toContain('decision = "block" { block_fired }');
    expect(result.rego).toContain('decision = "escalate" { escalate_fired; not block_fired }');
    expect(result.rego).toContain('decision = "audit" { audit_fired; not block_fired; not escalate_fired }');
    expect(result.rego).toContain("rule_id = sort([id | blocks[id]])[0] { block_fired }");
    expect(result.rego).toContain("rule_id = sort([id | escalates[id]])[0] { escalate_fired; not block_fired }");
    expect(result.rego).toContain("rule_id = sort([id | audits[id]])[0] { audit_fired; not block_fired; not escalate_fired }");
    expect(result.rego).toContain("reason = reasons[rule_id]");
    // reasons map carries both rules' reasons + the default
    expect(result.rego).toContain('"block_shell": "Shell injection blocked"');
    expect(result.rego).toContain('"low_trust": "Trust too low"');
    expect(result.rego).toContain('"builder_default_t": "nothing matched"');
    // audits is unused by this graph -> gets the safe empty-set stub (no undefined-var OPA reject)
    expect(result.rego).toContain("audits[id] { id := [][_] }");
  });

  it("is deterministic: compiling the same graph twice yields identical strings", () => {
    const a = compileGraph(TWO_RULE_GRAPH).rego;
    const b = compileGraph(TWO_RULE_GRAPH).rego;
    expect(a).toBe(b);
    expect(a.length).toBeGreaterThan(0);

    const c = compileGraph(FIXTURE_GRAPH).rego;
    const d = compileGraph(FIXTURE_GRAPH).rego;
    expect(c).toBe(d);
  });

  it("embeds the graph as base64 and decodes it back to a deep-equal of the input graph", () => {
    const result = compileGraph(FIXTURE_GRAPH);
    const decoded = extractEmbeddedGraph(result.rego);
    expect(decoded).toEqual(FIXTURE_GRAPH);
  });

  it("never emits data.* references or http.send, across every fixture used in this file", () => {
    for (const graph of [FIXTURE_GRAPH, TWO_RULE_GRAPH]) {
      const { rego } = compileGraph(graph);
      expect(rego).not.toMatch(/\bdata\./);
      expect(rego).not.toMatch(/http\.send/);
    }
  });
});

describe("builderCompile — compile-time errors (no rego emitted)", () => {
  it("rejects an empty rule_id", () => {
    const result = compileGraph(
      graphWith([{ id: "r1", decision: "block", ruleId: "", reason: "x", conditions: [[{ type: "detector", detector: "pii" }]] }])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["empty_rule_id"]);
  });

  it("rejects an empty reason", () => {
    const result = compileGraph(
      graphWith([{ id: "r1", decision: "block", ruleId: "a", reason: "  ", conditions: [[{ type: "detector", detector: "pii" }]] }])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["empty_reason"]);
  });

  it("rejects a duplicate rule_id across rules", () => {
    const result = compileGraph(
      graphWith([
        { id: "r1", decision: "block", ruleId: "dup", reason: "x", conditions: [[{ type: "detector", detector: "pii" }]] },
        { id: "r2", decision: "audit", ruleId: "dup", reason: "y", conditions: [[{ type: "detector", detector: "sql_injection" }]] }
      ])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["duplicate_rule_id"]);
  });

  it("rejects a rule with zero condition rows", () => {
    const result = compileGraph(graphWith([{ id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [] }]));
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["empty_conditions"]);
  });

  it("rejects a rule with an empty AND-row", () => {
    const result = compileGraph(graphWith([{ id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[]] }]));
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["empty_conditions"]);
  });

  it("rejects an empty keyword list", () => {
    const result = compileGraph(
      graphWith([
        { id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[{ type: "keyword", keywords: [], target: "tool" }]] }
      ])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["empty_keyword_list"]);
  });

  it("rejects an empty tool list", () => {
    const result = compileGraph(
      graphWith([{ id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[{ type: "toolIn", tools: [] }]] }])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["empty_tool_list"]);
  });

  it("rejects a user ruleId equal to the generated default rule id (builder_default_<token>)", () => {
    // graphWith() defaults to agentClass "t" -> token "t" -> defaultRuleId "builder_default_t".
    const result = compileGraph(
      graphWith([
        { id: "r1", decision: "block", ruleId: "builder_default_t", reason: "x", conditions: [[{ type: "detector", detector: "pii" }]] }
      ])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["reserved_default_rule_id"]);
  });

  it("rejects a threshold of 0 (must be > 0)", () => {
    const result = compileGraph(
      graphWith([{ id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[{ type: "trustBelow", threshold: 0 }]] }])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["threshold_out_of_range"]);
  });

  it("rejects a threshold above 1", () => {
    const result = compileGraph(
      graphWith([{ id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[{ type: "trustBelow", threshold: 1.5 }]] }])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["threshold_out_of_range"]);
  });

  it("accepts a threshold of exactly 1 (upper bound is inclusive)", () => {
    const result = compileGraph(
      graphWith([{ id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[{ type: "trustBelow", threshold: 1 }]] }])
    );
    expect(result.errors).toEqual([]);
    expect(result.rego).not.toBe("");
  });

  it("rejects a graph engineered to exceed the 500-line budget, reporting the real line count", () => {
    const rules: BuilderRule[] = [];
    for (let i = 0; i < 150; i++) {
      rules.push({
        id: `r${i}`,
        decision: "block",
        ruleId: `rule_${i}`,
        reason: `reason ${i}`,
        conditions: [[{ type: "toolIn", tools: [`tool_${i}`] }]]
      });
    }
    const result = compileGraph(graphWith(rules));
    expect(result.rego).toBe("");
    expect(result.errors).toHaveLength(1);
    expect(result.errors[0].code).toBe("budget_exceeded_lines");
    expect(result.stats.lines).toBeGreaterThan(BUDGET_MAX_LINES);
    expect(result.errors[0].message).toContain(String(result.stats.lines));
  });
});

// A small hand-written rego with no builder header at all — stands in for comprehensive.rego-style
// composer/hand-authored policies that were never produced by the Visual Policy Builder.
const NON_BUILDER_REGO = `package norviq.hand_authored

default decision = "allow"
default rule_id = "none"
default reason = "no match"

decision = "block" {
    input.tool_name == "execute_sql"
}
`;

describe("builderCompile — detachmentStatusOf", () => {
  it('returns "attached" for a freshly compiled rego (body still hashes to the embedded header hash)', () => {
    const { rego, errors } = compileGraph(FIXTURE_GRAPH);
    expect(errors).toEqual([]);
    expect(detachmentStatusOf(rego)).toBe("attached");
  });

  it('returns "detached" after a single body byte is hand-mutated post-compile', () => {
    const { rego, errors } = compileGraph(FIXTURE_GRAPH);
    expect(errors).toEqual([]);
    // Flip one character deep in the body (well after the header/hash lines) without touching the
    // embedded graph blob or hash comment — simulates a hand edit to the live rego.
    const bodyNeedle = 'blocks["builder_sql_block"]';
    const idx = rego.indexOf(bodyNeedle);
    expect(idx).toBeGreaterThan(-1);
    const mutated = rego.slice(0, idx) + 'blocks["builder_SQL_block"]' + rego.slice(idx + bodyNeedle.length);
    expect(mutated).not.toBe(rego);
    expect(detachmentStatusOf(mutated)).toBe("detached");
  });

  it('returns "not-builder" for a rego with no `# nrvq-builder-graph/v1:` header (e.g. comprehensive.rego-style)', () => {
    expect(detachmentStatusOf(NON_BUILDER_REGO)).toBe("not-builder");
  });
});

// ==== Phase 2b: sourceVerb / paramRegex / not condition types =====================================
// The live OPA decision-flip for a sourceVerb(postgresql,delete) fixture is proven manually (opa check
// --v0-compatible + opa eval + a real kind-cluster round trip, see the Phase 2b execution report) — same
// doctrine as the round-A fixture above: these unit tests pin the compiled SHAPE, not a substitute for
// that live proof.

const SOURCEVERB_GRAPH: BuilderGraph = graphWith([
  {
    id: "r1",
    decision: "block",
    ruleId: "block_pg_delete",
    reason: "Blocked a destructive verb on PostgreSQL",
    conditions: [[{ type: "sourceVerb", source: "postgresql", verb: "delete" }]]
  }
]);

describe("builderCompile — sourceVerb condition (Phase 2b)", () => {
  it("compiles to a bld_srcverb_<source>_<verb> predicate with postgresql/delete's exact fragment set, sorted", () => {
    const result = compileGraph(SOURCEVERB_GRAPH);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain("bld_srcverb_postgresql_delete {");
    // postgresql delete = [delete, drop, truncate, purge] per the capability mirror, sorted alphabetically.
    expect(result.rego).toContain('frag := {"delete", "drop", "purge", "truncate"}[_]');
    expect(result.rego).toContain("contains(lower(input.tool_name), frag)");
    // The rule body references the predicate (unnegated).
    expect(result.rego).toMatch(/blocks\["block_pg_delete"\] \{\n {4}input\.agent\.agent_class == "t"\n {4}bld_srcverb_postgresql_delete\n\}/);
  });

  it("is opa-safe (no data.*/http.send) and deterministic across repeated compiles", () => {
    const a = compileGraph(SOURCEVERB_GRAPH);
    const b = compileGraph(SOURCEVERB_GRAPH);
    expect(a.rego).toBe(b.rego);
    expect(a.rego.length).toBeGreaterThan(0);
    expect(a.rego).not.toMatch(/\bdata\./);
    expect(a.rego).not.toMatch(/http\.send/);
  });

  it("dedupes a repeated (source,verb) pair into exactly ONE predicate definition across two rules", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[{ type: "sourceVerb", source: "postgresql", verb: "delete" }]]
      },
      {
        id: "r2",
        decision: "escalate",
        ruleId: "b",
        reason: "y",
        conditions: [[{ type: "sourceVerb", source: "postgresql", verb: "delete" }]]
      }
    ]);
    const { rego, errors } = compileGraph(graph);
    expect(errors).toEqual([]);
    expect(rego.split("bld_srcverb_postgresql_delete {").length - 1).toBe(1);
    // Both rules still each reference it.
    expect(rego).toContain('blocks["a"]');
    expect(rego).toContain('escalates["b"]');
  });

  it("rejects a (source,verb) pair the capability mirror does not expose (invalid_source_verb) — e.g. smtp has no delete verb", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[{ type: "sourceVerb", source: "smtp", verb: "delete" }]]
      }
    ]);
    const result = compileGraph(graph);
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["invalid_source_verb"]);
  });

  it("rejects an unknown source entirely (invalid_source_verb)", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[{ type: "sourceVerb", source: "mongodb", verb: "read" }]]
      }
    ]);
    const result = compileGraph(graph);
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["invalid_source_verb"]);
  });
});

const PARAMREGEX_GRAPH: BuilderGraph = graphWith([
  {
    id: "r1",
    decision: "block",
    ruleId: "block_select_users",
    reason: "Suspicious SELECT against the users table",
    conditions: [[{ type: "paramRegex", field: "query", pattern: "^SELECT.*FROM users$" }]]
  }
]);

describe("builderCompile — paramRegex condition (Phase 2b)", () => {
  it("compiles to a bld_paramregex_<n> predicate over input.tool_params[field] via regex.match(pattern, val)", () => {
    const result = compileGraph(PARAMREGEX_GRAPH);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain("bld_paramregex_0 {");
    expect(result.rego).toContain('val := input.tool_params["query"]');
    expect(result.rego).toContain("is_string(val)");
    expect(result.rego).toContain('regex.match("^SELECT.*FROM users$", val)');
    expect(result.rego).toContain("bld_paramregex_0");
    // A single regex.match call -> the existing regexOps counter (computeStats) picks it up automatically.
    expect(result.stats.regexOps).toBe(1);
  });

  it("is opa-safe (no data.*/http.send) and deterministic across repeated compiles", () => {
    const a = compileGraph(PARAMREGEX_GRAPH);
    const b = compileGraph(PARAMREGEX_GRAPH);
    expect(a.rego).toBe(b.rego);
    expect(a.rego).not.toMatch(/\bdata\./);
    expect(a.rego).not.toMatch(/http\.send/);
  });

  it("assigns distinct, stable indices to multiple paramRegex conditions in one graph", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[
          { type: "paramRegex", field: "query", pattern: "DROP" },
          { type: "paramRegex", field: "url", pattern: "^https://" }
        ]]
      }
    ]);
    const { rego, errors } = compileGraph(graph);
    expect(errors).toEqual([]);
    expect(rego).toContain("bld_paramregex_0 {");
    expect(rego).toContain("bld_paramregex_1 {");
    expect(rego.indexOf("bld_paramregex_0 {")).toBeLessThan(rego.indexOf("bld_paramregex_1 {"));
  });

  it("rejects an empty field (paramRegex_invalid), no rego emitted", () => {
    const result = compileGraph(
      graphWith([
        { id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[{ type: "paramRegex", field: "   ", pattern: "abc" }]] }
      ])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["paramRegex_invalid"]);
  });

  it("rejects a pattern that does not compile as a regular expression (paramRegex_invalid), no rego emitted", () => {
    const result = compileGraph(
      graphWith([
        { id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[{ type: "paramRegex", field: "q", pattern: "(unclosed" }]] }
      ])
    );
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["paramRegex_invalid"]);
  });

  it("trips the 25-regex-op budget with 26 valid paramRegex conditions and reports the real op count", () => {
    const rules: BuilderRule[] = [];
    for (let i = 0; i < 26; i++) {
      rules.push({
        id: `r${i}`,
        decision: "block",
        ruleId: `px_${i}`,
        reason: `reason ${i}`,
        conditions: [[{ type: "paramRegex", field: `field_${i}`, pattern: `pattern_${i}` }]]
      });
    }
    const result = compileGraph(graphWith(rules));
    expect(result.rego).toBe("");
    expect(result.errors).toHaveLength(1);
    expect(result.errors[0].code).toBe("budget_exceeded_regex_ops");
    expect(result.stats.regexOps).toBe(26);
    expect(result.errors[0].message).toContain("26");
  });
});

describe("builderCompile — not condition (Phase 2b)", () => {
  it("negates a detector condition with a leading `not ` while still emitting the detector's own predicate block", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[{ type: "not", inner: { type: "detector", detector: "sql_injection" } }]]
      }
    ]);
    const result = compileGraph(graph);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain("not bld_sql_injection");
    expect(result.rego).toContain("bld_sql_injection {");
  });

  it("negates a sourceVerb condition, still emitting its predicate block", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[{ type: "not", inner: { type: "sourceVerb", source: "postgresql", verb: "read" } }]]
      }
    ]);
    const result = compileGraph(graph);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain("not bld_srcverb_postgresql_read");
    expect(result.rego).toContain("bld_srcverb_postgresql_read {");
  });

  it("negates a paramRegex condition, still emitting its predicate block", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[{ type: "not", inner: { type: "paramRegex", field: "q", pattern: "^SELECT" } }]]
      }
    ]);
    const result = compileGraph(graph);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain("not bld_paramregex_0");
    expect(result.rego).toContain("bld_paramregex_0 {");
  });

  it("negates a keyword condition (function-call form)", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[{ type: "not", inner: { type: "keyword", keywords: ["password"], target: "params" } }]]
      }
    ]);
    const result = compileGraph(graph);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain('not bld_kw_hit_params(["password"])');
  });

  it("negates a toolIn condition (set-membership form)", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[{ type: "not", inner: { type: "toolIn", tools: ["drop_table"] } }]]
      }
    ]);
    const result = compileGraph(graph);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain('not {"drop_table"}[input.tool_name]');
  });

  it("negates a trustBelow comparison exactly as the brief specifies", () => {
    const graph = graphWith([
      { id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[{ type: "not", inner: { type: "trustBelow", threshold: 0.4 } }]] }
    ]);
    const result = compileGraph(graph);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain("not input.agent.trust_score < 0.4");
  });

  it("rejects not-of-not as a single not_double_negation error, no rego emitted", () => {
    const graph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "a",
        reason: "x",
        conditions: [[{ type: "not", inner: { type: "not", inner: { type: "detector", detector: "pii" } } }]]
      }
    ]);
    const result = compileGraph(graph);
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["not_double_negation"]);
  });

  it("is deterministic across repeated compiles", () => {
    const graph = graphWith([
      { id: "r1", decision: "block", ruleId: "a", reason: "x", conditions: [[{ type: "not", inner: { type: "toolIn", tools: ["drop_table"] } }]] }
    ]);
    const a = compileGraph(graph).rego;
    const b = compileGraph(graph).rego;
    expect(a).toBe(b);
    expect(a.length).toBeGreaterThan(0);
  });
});

describe("builderCompile — detachmentStatusOf stays correct with Phase 2b condition types", () => {
  it('returns "attached" for a freshly compiled graph combining sourceVerb + paramRegex + not', () => {
    const graph: BuilderGraph = graphWith([
      {
        id: "r1",
        decision: "block",
        ruleId: "combo_rule",
        reason: "Combines every Phase 2b condition type",
        conditions: [
          [
            { type: "sourceVerb", source: "postgresql", verb: "delete" },
            { type: "paramRegex", field: "query", pattern: "^SELECT" },
            { type: "not", inner: { type: "detector", detector: "sql_injection" } }
          ]
        ]
      }
    ]);
    const { rego, errors } = compileGraph(graph);
    expect(errors).toEqual([]);
    expect(detachmentStatusOf(rego)).toBe("attached");

    // And round-trips through the embedded graph blob exactly, same doctrine as the round-A fixture.
    const decoded = extractEmbeddedGraph(rego);
    expect(decoded).toEqual(graph);
  });
});

// ==== Phase 2c: Intent Allowlist mode =============================================================
// A whole-policy DEFAULT-DENY shape (allow only the listed tools, block everything else) — a MODE,
// not another composable condition type, mirroring the server's `norviq/api/threat_intent.py
// generate_intent_rego` (read-only reference) to the shape the builder is allowed to emit: package
// `norviq.intent.<token>` — the documented namespace prefix (docs.norviq.dev/guides/writing-policies/)
// the server generator itself uses, so the server's own governance-classification (coverage.py's
// `_parse_agent_policy`, threats.py's `_governing_policies`) recognizes a builder-authored allowlist —
// and WITHOUT the server's `learned_verbs` feature (server-side registry data this client-side compiler
// has no access to). The live OPA decision-flip (opa check
// --v0-compatible + opa eval + a real kind-cluster POST /policies/evaluate round trip) is proven
// manually, same doctrine as every other fixture in this file — see the Phase 2c execution report.

function allowlistGraph(
  agentClass: string,
  tools: string[],
  refinements: Partial<{ readonly: boolean; egress: boolean; scope: boolean; rate: boolean }> = {}
): BuilderGraph {
  return {
    schemaVersion: 1,
    scope: { kind: "class", agentClass },
    mode: "allowlist",
    rules: [],
    defaults: { decision: "allow", reason: "n/a" },
    allowlist: {
      tools,
      refinements: {
        readonly: !!refinements.readonly,
        egress: !!refinements.egress,
        scope: !!refinements.scope,
        rate: !!refinements.rate
      }
    }
  };
}

describe("builderCompile — Intent Allowlist mode (Phase 2c) — shape", () => {
  it("compiles a 2-tool allowlist with no refinements to the default-deny shape (package, default triple, allow sets, membership, allow/refinement-mismatch rules)", () => {
    const graph = allowlistGraph("p2c-verify", ["search_docs", "get_order"]);
    const result = compileGraph(graph);
    expect(result.errors).toEqual([]);

    expect(result.rego).toContain("package norviq.intent.p2c_verify");
    expect(result.rego).toContain('default decision = "block"');
    expect(result.rego).toContain('default rule_id = "intent_default_deny"');
    expect(result.rego).toContain('default reason = "Blocked: tool is not in the intended allowlist for p2c-verify"');
    expect(result.rego).toContain('allow_names = {"get_order", "search_docs"}');
    expect(result.rego).toContain('allow_skeletons = {"get_order", "search_docs"}');
    expect(result.rego).toContain("in_allowlist { allow_names[lower(input.tool_name)] }");
    expect(result.rego).toContain("in_allowlist { allow_skeletons[input.tool_name_normalized] }");
    expect(result.rego).toContain("allow_intent {");
    expect(result.rego).toContain('    input.agent.agent_class == "p2c-verify"');
    expect(result.rego).toContain("    in_allowlist");
    expect(result.rego).toContain('denied { input.agent.agent_class == "p2c-verify"; not allow_intent }');
    expect(result.rego).toContain('decision = "allow" { allow_intent }');
    expect(result.rego).toContain('rule_id = "intent_allow_p2c_verify" { allow_intent }');
    expect(result.rego).toContain('reason = "Allowed: tool in the intended allowlist for p2c-verify" { allow_intent }');
    // the refinement-mismatch block rule (required by the server's validate_rego_source: a reachable
    // `decision = "block" { ... }` whose body isn't literally "false").
    expect(result.rego).toContain('decision = "block" { denied; in_allowlist }');
    expect(result.rego).toContain('rule_id = "intent_refinement_mismatch" { denied; in_allowlist }');
    expect(result.rego).toContain(
      'reason = sprintf("Blocked: %s is allowlisted for p2c-verify but fails an enabled refinement (e.g. no-external-egress)", [input.tool_name]) { denied; in_allowlist }'
    );

    // No refinement enabled -> none of the toggle helper vocabularies/guards are emitted.
    expect(result.rego).not.toContain("read_verbs");
    expect(result.rego).not.toContain("egress_tools");
    expect(result.rego).not.toContain("in_scope");
    expect(result.rego).not.toContain("rate_within");

    // Embeds the graph blob + hash header exactly like rules-mode (detachment/round-trip both work).
    expect(result.rego).toMatch(/^# nrvq-builder-graph\/v1: /m);
    expect(result.rego).toMatch(/^# nrvq-builder-hash: [0-9a-f]{8}$/m);
    expect(extractEmbeddedGraph(result.rego)).toEqual(graph);
  });

  it("is opa-safe (no data.*/http.send) with zero regex ops (no regex.match is ever emitted for allowlist mode)", () => {
    const graph = allowlistGraph("p2c-verify", ["search_docs", "get_order"], { readonly: true });
    const { rego, errors, stats } = compileGraph(graph);
    expect(errors).toEqual([]);
    expect(rego).not.toMatch(/\bdata\./);
    expect(rego).not.toMatch(/http\.send/);
    expect(stats.regexOps).toBe(0);
  });

  it("is deterministic: compiling the same allowlist graph twice yields byte-identical rego", () => {
    const graph = allowlistGraph("p2c-verify", ["search_docs", "get_order", "translate_text"], {
      readonly: true,
      scope: true
    });
    const a = compileGraph(graph).rego;
    const b = compileGraph(graph).rego;
    expect(a).toBe(b);
    expect(a.length).toBeGreaterThan(0);
  });

  it("normalizes tool names into allow_names/allow_skeletons: lower-cased, deduped, and sorted regardless of input case/order/duplicates", () => {
    const graph = allowlistGraph("p2c-verify", ["Get_Order", "search_docs", "SEARCH_DOCS", "  get_order  "]);
    const result = compileGraph(graph);
    expect(result.errors).toEqual([]);
    // Exactly the two distinct lower-cased names, sorted.
    expect(result.rego).toContain('allow_names = {"get_order", "search_docs"}');
  });
});

describe("builderCompile — Intent Allowlist refinement toggles (Phase 2c)", () => {
  it("readonly toggle adds the read_verbs helper block and the is_read guard", () => {
    const result = compileGraph(allowlistGraph("p2c-verify", ["search_docs"], { readonly: true }));
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain(
      'read_verbs = {"read", "get", "list", "search", "fetch", "describe", "query", "lookup", "view", "find", "scan", "count"}'
    );
    expect(result.rego).toContain('tool_verb := split(lower(input.tool_name), "_")[0]');
    expect(result.rego).toContain('tool_verb_norm := split(lower(input.tool_name_normalized), "_")[0]');
    expect(result.rego).toContain("is_read { read_verbs[tool_verb] }");
    expect(result.rego).toContain("is_read { read_verbs[tool_verb_norm] }");
    expect(result.rego).toContain("    is_read");
    // The other three refinements' vocabularies are absent.
    expect(result.rego).not.toContain("egress_tools");
    expect(result.rego).not.toContain("in_scope");
    expect(result.rego).not.toContain("rate_within");
  });

  it("egress toggle adds the egress_tools helper block and the `not is_egress` guard", () => {
    const result = compileGraph(allowlistGraph("p2c-verify", ["search_docs"], { egress: true }));
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain(
      'egress_tools = {"send_email", "send_sms", "send_message", "http_post", "http_request", "webhook", "post_webhook", "upload", "upload_file", "export", "export_data", "s3_put", "put_object", "publish", "smtp", "notify_external", "call_api", "fetch_url"}'
    );
    expect(result.rego).toContain("is_egress { egress_tools[lower(input.tool_name)] }");
    expect(result.rego).toContain("is_egress { egress_tools[lower(input.tool_name_normalized)] }");
    expect(result.rego).toContain("    not is_egress");
    expect(result.rego).not.toContain("read_verbs");
    expect(result.rego).not.toContain("in_scope");
    expect(result.rego).not.toContain("rate_within");
  });

  it("scope toggle adds the in_scope/_cross_namespace helper block and the in_scope guard", () => {
    const result = compileGraph(allowlistGraph("p2c-verify", ["search_docs"], { scope: true }));
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain("in_scope { not _cross_namespace }");
    expect(result.rego).toContain("_cross_namespace {");
    expect(result.rego).toContain("ns := input.tool_params[k]");
    expect(result.rego).toContain('ns != input.agent.namespace');
    expect(result.rego).toContain('_looks_like_namespace_key(k) { lower(k) == "namespace" }');
    expect(result.rego).toContain('_looks_like_namespace_key(k) { lower(k) == "ns" }');
    expect(result.rego).toContain('_looks_like_namespace_key(k) { lower(k) == "tenant" }');
    expect(result.rego).toContain("    in_scope");
    expect(result.rego).not.toContain("read_verbs");
    expect(result.rego).not.toContain("egress_tools");
    expect(result.rego).not.toContain("rate_within");
  });

  it("rate toggle adds the rate_within helper block and the rate_within guard", () => {
    const result = compileGraph(allowlistGraph("p2c-verify", ["search_docs"], { rate: true }));
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain("rate_within { input.call_depth <= 8 }");
    expect(result.rego).toContain("    rate_within");
    expect(result.rego).not.toContain("read_verbs");
    expect(result.rego).not.toContain("egress_tools");
    expect(result.rego).not.toContain("in_scope");
  });

  it("emits every enabled refinement's guard line in the fixed class/in_allowlist/readonly/egress/scope/rate order", () => {
    const result = compileGraph(
      allowlistGraph("p2c-verify", ["search_docs"], { readonly: true, egress: true, scope: true, rate: true })
    );
    expect(result.errors).toEqual([]);
    const match = result.rego.match(/allow_intent \{\n([\s\S]*?)\n\}/);
    expect(match).not.toBeNull();
    const guardLines = match![1].split("\n").map((l) => l.trim());
    expect(guardLines).toEqual(["input.agent.agent_class == \"p2c-verify\"", "in_allowlist", "is_read", "not is_egress", "in_scope", "rate_within"]);
  });
});

describe("builderCompile — Intent Allowlist empty allowlist (Phase 2c)", () => {
  it("an empty tool list compiles successfully (no errors) — a valid, intentional deny-everything allowlist", () => {
    const result = compileGraph(allowlistGraph("p2c-verify", []));
    expect(result.errors).toEqual([]);
    expect(result.rego).not.toBe("");
    expect(result.rego).toContain("allow_names = {}");
    expect(result.rego).toContain("allow_skeletons = {}");
    expect(result.rego).toContain("(empty — denies every tool for this class)");
  });
});

describe("builderCompile — Intent Allowlist compile-time errors (Phase 2c)", () => {
  it("rejects a malformed allowlist (tools is not an array) — no rego emitted", () => {
    const graph = allowlistGraph("p2c-verify", []);
    (graph.allowlist as unknown as { tools: unknown }).tools = "not-an-array";
    const result = compileGraph(graph);
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["invalid_allowlist"]);
  });

  it("rejects a missing allowlist object entirely when mode is allowlist — no rego emitted", () => {
    const graph = allowlistGraph("p2c-verify", []);
    delete (graph as { allowlist?: unknown }).allowlist;
    const result = compileGraph(graph);
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["invalid_allowlist"]);
  });

  it("rejects a tool name that is empty (whitespace-only) after trim, while a non-empty overall list is otherwise fine", () => {
    const result = compileGraph(allowlistGraph("p2c-verify", ["search_docs", "   "]));
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["empty_allowlist_tool"]);
  });
});

describe("builderCompile — Intent Allowlist detachment + mode back-compat (Phase 2c)", () => {
  it('detachmentStatusOf returns "attached" for a freshly compiled allowlist-mode graph', () => {
    const graph = allowlistGraph("p2c-verify", ["search_docs", "get_order"], { readonly: true, scope: true });
    const { rego, errors } = compileGraph(graph);
    expect(errors).toEqual([]);
    expect(detachmentStatusOf(rego)).toBe("attached");
  });

  it('reports "detached" after a single body byte is hand-mutated post-compile, same as rules mode', () => {
    const graph = allowlistGraph("p2c-verify", ["search_docs"]);
    const { rego, errors } = compileGraph(graph);
    expect(errors).toEqual([]);
    const needle = 'allow_names = {"search_docs"}';
    const idx = rego.indexOf(needle);
    expect(idx).toBeGreaterThan(-1);
    const mutated = rego.slice(0, idx) + 'allow_names = {"search_DOCS"}' + rego.slice(idx + needle.length);
    expect(detachmentStatusOf(mutated)).toBe("detached");
  });

  it('mode defaults to "rules" when absent — an existing rules-mode graph with no `mode` field still compiles the unchanged rules path (back-compat)', () => {
    // FIXTURE_GRAPH (defined at the top of this file, used by the round-A golden-snapshot test) has no
    // `mode` field at all — exactly the shape every pre-Phase-2c graph object literal has.
    expect((FIXTURE_GRAPH as { mode?: unknown }).mode).toBeUndefined();
    const result = compileGraph(FIXTURE_GRAPH);
    expect(result.errors).toEqual([]);
    // Still the rules-mode shape: partial-set blocks + the verbatim resolver, NOT the allowlist shape.
    expect(result.rego).toContain('blocks["builder_sql_block"]');
    expect(result.rego).toContain("block_fired { blocks[_] }");
    expect(result.rego).not.toContain("intent_default_deny");
    expect(result.rego).not.toContain("allow_names");
    // Byte-identical to the pinned golden snapshot — mode's absence changed nothing.
    expect(result.rego).toBe(FIXTURE_GOLDEN_REGO);
  });

  it('an explicit mode: "rules" behaves identically to an absent mode field', () => {
    const explicit: BuilderGraph = { ...FIXTURE_GRAPH, mode: "rules" };
    const result = compileGraph(explicit);
    expect(result.errors).toEqual([]);
    // Same body — but NOT byte-identical to FIXTURE_GOLDEN_REGO, since the embedded graph blob (and
    // therefore the body hash) now includes the extra `mode` key. Compare the body ignoring the blob/hash.
    const stripHeader = (s: string) => s.replace(/^# nrvq-builder-graph\/v1: .*$/m, "").replace(/^# nrvq-builder-hash: .*$/m, "");
    expect(stripHeader(result.rego)).toBe(stripHeader(FIXTURE_GOLDEN_REGO));
  });
});

// ==== Phase 3: namespace + workload tiers, and the reserved-scope guard (Item A, P1 fix) ============
// Grounding (advisor-verified, not re-derived here): the server's `resolve_policy_key` mints
// `namespace:<ns>` / `deployment:<name>` loader keys for the namespace/workload tiers, and
// `_collect_candidates` collects the namespace-tier candidate for EVERY call in that namespace
// (unconditional on agent_class) and the workload-tier candidate ONLY via the loader key (OPA's own
// input carries no workload field to self-guard on) — see builderCompile.ts's own "scope / tier
// helpers" section header comment for the full mapping this section's assertions pin.

function nsGraphWith(
  namespace: string,
  rules: BuilderRule[],
  defaults: BuilderGraph["defaults"] = { decision: "allow", reason: "d" }
): BuilderGraph {
  return { schemaVersion: 1, scope: { kind: "namespace", namespace }, rules, defaults };
}

function wlGraphWith(
  workloadName: string,
  rules: BuilderRule[],
  defaults: BuilderGraph["defaults"] = { decision: "allow", reason: "d" }
): BuilderGraph {
  return { schemaVersion: 1, scope: { kind: "workload", workloadName }, rules, defaults };
}

const ONE_BLOCK_RULE: BuilderRule[] = [
  { id: "r1", decision: "block", ruleId: "block_wipe", reason: "Blocked a destructive tool", conditions: [[{ type: "toolIn", tools: ["wipe_index"] }]] }
];

describe("builderCompile — loaderKeyFor / scopeIdentifier (Phase 3)", () => {
  it("class tier: loader key is the class verbatim", () => {
    const scope: BuilderScope = { kind: "class", agentClass: "report-gen" };
    expect(loaderKeyFor(scope)).toBe("report-gen");
    expect(scopeIdentifier(scope)).toBe("report-gen");
  });
  it("namespace tier: loader key is namespace:<ns>", () => {
    const scope: BuilderScope = { kind: "namespace", namespace: "default" };
    expect(loaderKeyFor(scope)).toBe("namespace:default");
    expect(scopeIdentifier(scope)).toBe("default");
  });
  it("workload tier: loader key is deployment:<name> (deployment kind only)", () => {
    const scope: BuilderScope = { kind: "workload", workloadName: "checkout" };
    expect(loaderKeyFor(scope)).toBe("deployment:checkout");
    expect(scopeIdentifier(scope)).toBe("checkout");
  });
});

describe("builderCompile — namespace tier (Phase 3)", () => {
  it("compiles with an input.agent.namespace guard and NO agent_class guard anywhere in the module", () => {
    const result = compileGraph(nsGraphWith("default", ONE_BLOCK_RULE));
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain('input.agent.namespace == "default"');
    expect(result.rego).not.toMatch(/agent_class ==/);
    expect(result.rego).toContain("package norviq.custom.ns_default");
    expect(result.rego).toContain('default rule_id = "builder_default_ns_default"');
  });

  it("is deterministic and opa-safe (no data.*/http.send)", () => {
    const a = compileGraph(nsGraphWith("default", ONE_BLOCK_RULE));
    const b = compileGraph(nsGraphWith("default", ONE_BLOCK_RULE));
    expect(a.rego).toBe(b.rego);
    expect(a.rego.length).toBeGreaterThan(0);
    expect(a.rego).not.toMatch(/\bdata\./);
    expect(a.rego).not.toMatch(/http\.send/);
  });

  it('round-trips through the embedded graph blob and reports "attached" via detachmentStatusOf', () => {
    const graph = nsGraphWith("default", ONE_BLOCK_RULE);
    const { rego, errors } = compileGraph(graph);
    expect(errors).toEqual([]);
    expect(extractEmbeddedGraph(rego)).toEqual(graph);
    expect(detachmentStatusOf(rego)).toBe("attached");
  });

  it("intent-allowlist mode: the allow_intent/denied guards use input.agent.namespace, not agent_class", () => {
    const graph: BuilderGraph = {
      schemaVersion: 1,
      scope: { kind: "namespace", namespace: "default" },
      mode: "allowlist",
      rules: [],
      defaults: { decision: "allow", reason: "n/a" },
      allowlist: { tools: ["search_docs"], refinements: { readonly: false, egress: false, scope: false, rate: false } }
    };
    const result = compileGraph(graph);
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain('input.agent.namespace == "default"');
    expect(result.rego).not.toMatch(/agent_class ==/);
    expect(result.rego).toContain("package norviq.intent.ns_default");
  });
});

describe("builderCompile — workload tier (Phase 3)", () => {
  it("compiles with an input.agent.namespace guard (sourced from the supplied targetNamespace) and NO agent_class guard", () => {
    const result = compileGraph(wlGraphWith("checkout", ONE_BLOCK_RULE), "prod-ns");
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain('input.agent.namespace == "prod-ns"');
    expect(result.rego).not.toMatch(/agent_class ==/);
    expect(result.rego).toContain("package norviq.custom.wl_checkout");
    expect(result.rego).toContain('default rule_id = "builder_default_wl_checkout"');
  });

  it("with no targetNamespace supplied, the guard is against the empty string (still valid rego, just unconditionally false at runtime)", () => {
    const result = compileGraph(wlGraphWith("checkout", ONE_BLOCK_RULE));
    expect(result.errors).toEqual([]);
    expect(result.rego).toContain('input.agent.namespace == ""');
  });

  it("is deterministic and opa-safe (no data.*/http.send)", () => {
    const a = compileGraph(wlGraphWith("checkout", ONE_BLOCK_RULE), "prod-ns");
    const b = compileGraph(wlGraphWith("checkout", ONE_BLOCK_RULE), "prod-ns");
    expect(a.rego).toBe(b.rego);
    expect(a.rego).not.toMatch(/\bdata\./);
    expect(a.rego).not.toMatch(/http\.send/);
  });

  it('round-trips through the embedded graph blob and reports "attached" via detachmentStatusOf', () => {
    const graph = wlGraphWith("checkout", ONE_BLOCK_RULE);
    const { rego, errors } = compileGraph(graph, "prod-ns");
    expect(errors).toEqual([]);
    expect(extractEmbeddedGraph(rego)).toEqual(graph); // targetNamespace isn't part of the graph itself
    expect(detachmentStatusOf(rego)).toBe("attached");
  });

  it("distinct package/default-rule-id from a same-named class or namespace tier (no collision)", () => {
    const wl = compileGraph(wlGraphWith("checkout", ONE_BLOCK_RULE), "ns");
    const ns = compileGraph(nsGraphWith("checkout", ONE_BLOCK_RULE));
    const cls = compileGraph({ schemaVersion: 1, scope: { kind: "class", agentClass: "checkout" }, rules: ONE_BLOCK_RULE, defaults: { decision: "allow", reason: "d" } });
    expect(wl.errors).toEqual([]);
    expect(ns.errors).toEqual([]);
    expect(cls.errors).toEqual([]);
    expect(wl.rego).toContain("package norviq.custom.wl_checkout");
    expect(ns.rego).toContain("package norviq.custom.ns_checkout");
    expect(cls.rego).toContain("package norviq.custom.checkout");
    const packages = [wl.rego, ns.rego, cls.rego].map((r) => r.match(/^package (\S+)$/m)![1]);
    expect(new Set(packages).size).toBe(3);
  });
});

describe("builderCompile — reserved-scope guard (Phase 3, Item A / P1 fix)", () => {
  const RESERVED_CLASSES = ["__baseline__", "__pack__", "__pack_override__", "__pack_weaken__", "__guardrail__", "__anything__"];

  RESERVED_CLASSES.forEach((reserved) => {
    it(`rejects "${reserved}" as a class-tier agent class (reserved_scope), no rego emitted`, () => {
      const graph: BuilderGraph = {
        schemaVersion: 1,
        scope: { kind: "class", agentClass: reserved },
        rules: ONE_BLOCK_RULE,
        defaults: { decision: "allow", reason: "d" }
      };
      const result = compileGraph(graph);
      expect(result.rego).toBe("");
      expect(result.errors.map((e) => e.code)).toContain("reserved_scope");
    });
  });

  it("rejects a class agent class containing ':' (would collide with the namespace:/deployment: key scheme)", () => {
    const graph: BuilderGraph = {
      schemaVersion: 1,
      scope: { kind: "class", agentClass: "namespace:default" },
      rules: ONE_BLOCK_RULE,
      defaults: { decision: "allow", reason: "d" }
    };
    const result = compileGraph(graph);
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toContain("reserved_scope");
  });

  it('rejects "__cluster__" as a namespace-tier target namespace, no rego emitted', () => {
    const result = compileGraph(nsGraphWith("__cluster__", ONE_BLOCK_RULE));
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["reserved_scope"]);
  });

  it('rejects "__cluster__" as the class tier\'s target namespace (2nd compileGraph argument)', () => {
    const graph: BuilderGraph = {
      schemaVersion: 1,
      scope: { kind: "class", agentClass: "report-gen" },
      rules: ONE_BLOCK_RULE,
      defaults: { decision: "allow", reason: "d" }
    };
    const result = compileGraph(graph, "__cluster__");
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["reserved_scope"]);
  });

  it('rejects "__cluster__" as the workload tier\'s target namespace', () => {
    const result = compileGraph(wlGraphWith("checkout", ONE_BLOCK_RULE), "__cluster__");
    expect(result.rego).toBe("");
    expect(result.errors.map((e) => e.code)).toEqual(["reserved_scope"]);
  });

  it("a normal, non-reserved class/namespace/workload compiles cleanly (no false positives)", () => {
    expect(
      compileGraph({ schemaVersion: 1, scope: { kind: "class", agentClass: "report-gen" }, rules: ONE_BLOCK_RULE, defaults: { decision: "allow", reason: "d" } })
        .errors
    ).toEqual([]);
    expect(compileGraph(nsGraphWith("default", ONE_BLOCK_RULE)).errors).toEqual([]);
    expect(compileGraph(wlGraphWith("checkout", ONE_BLOCK_RULE), "default").errors).toEqual([]);
    // A remediation-overlay-shaped class ("<class>__remediation__") is NOT reserved (single leading
    // underscore doctrine — isReservedScope only catches a DOUBLE leading underscore) — same doctrine
    // reservedScope.ts's own isRemediationOverlayClass documents.
    expect(
      compileGraph({
        schemaVersion: 1,
        scope: { kind: "class", agentClass: "report-gen__remediation__" },
        rules: ONE_BLOCK_RULE,
        defaults: { decision: "allow", reason: "d" }
      }).errors
    ).toEqual([]);
  });

  it("the reserved-scope error is reachable even from a graph shape that never went through the UI's own field-level guard (compiler is the true backstop)", () => {
    // Simulates a graph constructed programmatically (e.g. a saved-graph blob edited by hand, or a
    // future alternate UI) rather than through BuilderSheet's input field.
    const bypassGraph = JSON.parse(
      JSON.stringify({ schemaVersion: 1, scope: { kind: "class", agentClass: "__baseline__" }, rules: [], defaults: { decision: "allow", reason: "d" } })
    ) as BuilderGraph;
    const result = compileGraph(bypassGraph);
    expect(result.rego).toBe("");
    expect(result.errors.some((e) => e.code === "reserved_scope")).toBe(true);
  });
});
