// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Norviq Contributors
//
// The "New Policy" composer creates an ENFORCING agent-class policy for a MANUALLY-entered class
// (one with no running labeled deployment). The composer sheet has no rego editor, so it generates a
// small, valid, self-contained keyword-block policy here. The backend `apply` path requires a
// pre-saved policy (404 "save it first"), so for a brand-new class the composer CREATEs first
// (POST /api/v1/policies) — create() enforces directly on the read path.
//
// The generated rego satisfies the API's `validate_policy_create` guard: it has a reachable
// `decision = "block"|"escalate" { … }` rule plus `rule_id` and `reason`. It is TIGHTEN-ONLY next to
// the comprehensive baseline: non-matching calls return the default `allow`, and in the resolver's
// most-restrictive tie-break a baseline `block` always wins over an `allow`, so the policy can only
// ADD denials for its class, never weaken the baseline.

/** Rego package tokens must be `[a-z0-9_]`; fold anything else and never emit an empty token. */
export function sanitizeClassToken(cls: string): string {
  const t = (cls || "")
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return t || "class";
}

/** De-dupe, lower-case, trim and sort the block keywords (stable output → stable rego → clean diffs). */
export function normalizeKeywords(keywords: string[]): string[] {
  return [...new Set((keywords || []).map((k) => k.trim().toLowerCase()).filter(Boolean))].sort();
}

/**
 * Generate a self-contained enforcing rego policy for `agentClass` that blocks (or escalates) any tool
 * call for THAT class whose tool name or any string parameter contains one of `keywords`.
 * `mode` "audit" is not enforceable on its own (the API requires a block/escalate rule), so it maps to
 * a `block` decision — the caller still passes the chosen enforcement_mode as create metadata.
 */
export function composerRego(agentClass: string, mode: string, keywords: string[]): string {
  const cls = (agentClass || "").trim();
  const token = sanitizeClassToken(cls);
  const decision = mode === "escalate" ? "escalate" : "block";
  const kw = normalizeKeywords(keywords);
  const kwSet = kw.length ? `{${kw.map((k) => JSON.stringify(k)).join(", ")}}` : "set()";
  return `package norviq.composer.${token}

# GENERATED by the New Policy composer (manual agent-class entry) for class "${cls}".
# Blocks a tool call for this class when the tool name OR any string parameter contains a configured
# keyword. TIGHTEN-ONLY: non-matching calls fall through to the default allow; a baseline block always
# wins the resolver's most-restrictive tie-break, so this can only ADD denials for "${cls}".

default decision = "allow"
default rule_id = "composer_allow_${token}"
default reason = "Allowed: no composer keyword matched for ${cls}"

composer_keywords := ${kwSet}

_kw_hit(s) {
    is_string(s)
    some kw
    composer_keywords[kw]
    contains(lower(s), kw)
}

matched {
    input.agent.agent_class == "${cls}"
    _kw_hit(input.tool_name)
}
matched {
    input.agent.agent_class == "${cls}"
    some k
    _kw_hit(input.tool_params[k])
}

decision = "${decision}" { matched }
rule_id = "composer_block_${token}" { matched }
reason = "Blocked by composer policy for ${cls}: a configured keyword matched" { matched }
`;
}
