// SPDX-License-Identifier: Apache-2.0
import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { http, HttpResponse } from "msw";
import { setupServer } from "msw/node";
import { MemoryRouter } from "react-router-dom";
import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { PolicyCatalog } from "./PolicyCatalog";
import { AppProvider } from "../store/AppContext";
import { clearApiCache } from "../hooks/useApi";

// Monaco can't mount in jsdom — stub it so we can assert the editor surfaced.
vi.mock("@monaco-editor/react", () => ({
  default: ({ value }: { value?: string }) => <div data-testid="monaco-editor">{value}</div>
}));

const server = setupServer();
let deploymentsCalls = 0;
let deployments404 = false;

beforeAll(() => server.listen({ onUnhandledRequest: "bypass" }));
afterEach(() => {
  server.resetHandlers();
  clearApiCache();
  deploymentsCalls = 0;
  deployments404 = false;
});
afterAll(() => server.close());

function seedHandlers(policyTargetType: string | undefined) {
  const policy: Record<string, unknown> = {
    namespace: "default",
    agent_class: "customer-support",
    current_version: 1,
    rego_length: 120,
    priority: 700
  };
  if (policyTargetType !== undefined) policy.target_type = policyTargetType;
  server.use(
    http.get("/api/v1/policies", () => HttpResponse.json([policy])),
    http.get("/api/v1/deployments", () => {
      deploymentsCalls += 1;
      return HttpResponse.json([{ name: "customer-support", namespace: "default", agent_class: "customer-support" }]);
    }),
    http.get("/api/v1/policies/default/customer-support", () =>
      HttpResponse.json({ namespace: "default", agent_class: "customer-support", rego_source: "package norviq.strict\n", version: 1 })
    ),
    http.get("/api/v1/policies/default/customer-support/versions", () => HttpResponse.json([]))
  );
}

function renderPage(initialEntries: string[] = ["/"]) {
  return render(
    <MemoryRouter initialEntries={initialEntries}>
      <AppProvider>
        <PolicyCatalog />
      </AppProvider>
    </MemoryRouter>
  );
}

describe("PolicyCatalog (#3 / #4)", () => {
  it("opens the class policy in the editor (Monaco mounts) and groups it under Agent-Class", async () => {
    seedHandlers("class");
    renderPage();

    // Editor is the landing tab: the class policy file is listed and Monaco mounts.
    expect((await screen.findAllByText("customer-support.rego")).length).toBeGreaterThan(0);
    expect(screen.getByTestId("monaco-editor")).toBeInTheDocument();

    // It lands in the Agent-Class tier of the catalog (not "No class policies configured").
    fireEvent.click(screen.getByRole("button", { name: /^catalog$/i }));
    expect(await screen.findByText(/agent-class policies/i)).toBeInTheDocument();
    expect(screen.getAllByText("customer-support").length).toBeGreaterThan(0);
    expect(screen.queryByText(/no class policies configured/i)).not.toBeInTheDocument();

    // Fix 7: enforcing policies live under a distinct "Active policies" section with a right-aligned
    // status chip (quiet border-only pill), separate from the dry-run drafts panel.
    expect(screen.getByText(/active policies/i)).toBeInTheDocument();
    expect(screen.getByTestId("active-policies-mode")).toHaveTextContent(/Enforcing/i);
  });

  it("UX-CREATE bridge: 'Edit as raw rego' hands the composer's generated rego to the raw editor", async () => {
    seedHandlers("class");
    renderPage();
    await screen.findAllByText("customer-support.rego");

    // Open the GUIDED composer, name a brand-new class.
    fireEvent.click(screen.getByRole("button", { name: /new policy \(guided\)/i }));
    const classInput = await screen.findByPlaceholderText(/e\.g\. customer-support/i);
    fireEvent.change(classInput, { target: { value: "billing-bot" } });

    // Bridge into the raw editor.
    fireEvent.click(screen.getByRole("button", { name: /edit as raw rego/i }));

    // The composer closed and the raw editor now holds the COMPOSER-GENERATED rego for that class,
    // scoped to the class (package token is derived from it) — a guided draft graduated into raw authoring.
    await waitFor(() => {
      const editor = screen.getByTestId("monaco-editor");
      expect(editor).toHaveTextContent(/GENERATED by the New Policy composer/i);
      expect(editor).toHaveTextContent(/billing-bot/);
    });
    // Sidebar reflects raw-authoring mode.
    expect(screen.getByText("New policy (raw rego)")).toBeInTheDocument();
  });

  it("'View rego' expands each version's OWN source read-only", async () => {
    seedHandlers("class");
    server.use(
      http.get("/api/v1/policies/default/customer-support/versions", () =>
        HttpResponse.json([
          { version: 1, saved_by: "alice", saved_at: "2026-07-11T00:00:00Z", rego_source: "package norviq.v1_marker\n" },
          { version: 2, saved_by: "bob", saved_at: "2026-07-11T01:00:00Z", rego_source: "package norviq.v2_marker\n" }
        ])
      )
    );
    renderPage();
    await screen.findAllByText("customer-support.rego");
    fireEvent.click(screen.getByRole("button", { name: /^versions$/i }));
    // Expand v1's rego — its DISTINCT source shows (not the current policy's for every row).
    fireEvent.click(await screen.findByTestId("version-view-1"));
    await waitFor(() => expect(screen.getByTestId("version-rego-1")).toHaveTextContent("v1_marker"));
    expect(screen.queryByTestId("version-rego-2")).not.toBeInTheDocument();
  });

  it("the active-policy card reflects reality — health dot + last-applied time", async () => {
    // The list endpoint now returns last_applied so the Catalog card can show the policy is live + when it applied.
    const recent = new Date(Date.now() - 5 * 60_000).toISOString();
    server.use(
      http.get("/api/v1/policies", () =>
        HttpResponse.json([{
          namespace: "default", agent_class: "customer-support", target_type: "class",
          current_version: 3, rego_length: 120, priority: 700, mode: "block", last_applied: recent
        }])
      ),
      http.get("/api/v1/deployments", () => HttpResponse.json([])),
      http.get("/api/v1/policies/default/customer-support", () =>
        HttpResponse.json({ namespace: "default", agent_class: "customer-support", rego_source: "package norviq.strict\n", version: 3 })
      ),
      http.get("/api/v1/policies/default/customer-support/versions", () => HttpResponse.json([]))
    );
    renderPage();
    fireEvent.click(screen.getByRole("button", { name: /^catalog$/i }));
    // health dot (a listed policy IS loaded & enforcing) + the version + a "applied … ago" timestamp
    expect(await screen.findByLabelText(/loaded & enforcing/i)).toBeInTheDocument();
    expect(screen.getByText(/applied .*ago/i)).toBeInTheDocument();
    expect(screen.getByText(/v3 ·/i)).toBeInTheDocument();
  });

  it("defaults a target_type-less policy to class (UI defense-in-depth)", async () => {
    seedHandlers(undefined); // API omitted target_type
    renderPage();
    // Still opens in the editor — withTargetType() defaults agent_class policies to "class".
    expect((await screen.findAllByText("customer-support.rego")).length).toBeGreaterThan(0);
    expect(screen.getByTestId("monaco-editor")).toBeInTheDocument();
  });

  it("surfaces an intent draft as a dry-run row and never auto-enforces on review (feat/attack-graph)", async () => {
    seedHandlers("class");
    let applyCalled = false;
    let createCalled = false;
    server.use(
      // Selected namespace defaults to "all" → drafts fetched without ns param.
      http.get("/api/v1/threats/intent-drafts", () =>
        HttpResponse.json({
          drafts: [
            {
              draft_id: "d-1",
              ns: "default",
              cls: "billing-agent",
              enabled: ["deny_pii_exfil", "rate_limit"],
              covered_count: 3,
              total: 5,
              created_at: "2026-07-03T12:00:00Z",
              // Compliance provenance so the row is traceable to the originating control.
              source_framework: "owasp",
              source_control_id: "LLM07:2025",
              source_control_name: "System Prompt Leakage"
            }
          ],
          total: 1,
          returned: 1,
          offset: 0,
          limit: 15
        })
      ),
      http.get("/api/v1/threats/intent-drafts/d-1", () =>
        HttpResponse.json({
          draft_id: "d-1",
          ns: "default",
          cls: "billing-agent",
          rego: "package norviq.intent.billing\ndefault allow = false\n",
          enabled: ["deny_pii_exfil", "rate_limit"],
          covered_count: 3,
          total: 5,
          enforcement: "draft",
          source_framework: "owasp",
          source_control_id: "LLM07:2025",
          source_control_name: "System Prompt Leakage"
        })
      ),
      // Any enforce/create path is a hard failure for this test — it must NOT be hit automatically.
      http.post("/api/v1/policies/:ns/:cls/apply", () => {
        applyCalled = true;
        return HttpResponse.json({ applied: true });
      }),
      http.post("/api/v1/policies", () => {
        createCalled = true;
        return HttpResponse.json({});
      })
    );

    // Deep-link to the draft: ?intent_draft=d-1 loads the full rego for review.
    renderPage(["/?intent_draft=d-1"]);

    // The drafts section is clearly labeled dry-run and shows the draft row.
    expect(await screen.findByText(/intent drafts · dry-run/i)).toBeInTheDocument();
    expect(await screen.findByTestId("intent-draft-d-1")).toBeInTheDocument();
    expect(screen.getByText("billing-agent")).toBeInTheDocument();
    // Enabled constraints render as chips; coverage is shown.
    expect(screen.getByText("deny_pii_exfil")).toBeInTheDocument();
    expect(screen.getByText(/coverage 3\/5/i)).toBeInTheDocument();
    // The deep-linked draft auto-opens its generated rego read-only.
    expect(await screen.findByTestId("intent-draft-rego")).toHaveTextContent("package norviq.intent.billing");
    // The draft is traceable to its originating framework + control — on the row AND in the review header.
    expect(screen.getByTestId("intent-draft-source-d-1")).toHaveTextContent("from OWASP LLM · LLM07:2025 System Prompt Leakage");
    expect(await screen.findByTestId("intent-draft-source-header")).toHaveTextContent("OWASP LLM · LLM07:2025 System Prompt Leakage");

    // "Review & apply" only hands off to the existing editor — it must NOT call apply/create.
    fireEvent.click(screen.getByRole("button", { name: /review & apply/i }));
    await waitFor(() => expect(screen.getByTestId("monaco-editor")).toHaveTextContent("norviq.intent.billing"));
    expect(applyCalled).toBe(false);
    expect(createCalled).toBe(false);
  });

  it("a compliance-remediation draft's Review & apply targets the compound overlay key, never the base class", async () => {
    // The base class already has its OWN comprehensive enforcing policy — the fixture proves it survives.
    server.use(
      http.get("/api/v1/policies", () =>
        HttpResponse.json([
          {
            namespace: "default", agent_class: "report-gen", target_type: "class",
            current_version: 4, rego_length: 900, priority: 700, mode: "block"
          }
        ])
      ),
      http.get("/api/v1/deployments", () => HttpResponse.json([])),
      http.get("/api/v1/policies/default/report-gen", () =>
        HttpResponse.json({ namespace: "default", agent_class: "report-gen", rego_source: "package norviq.comprehensive\n", version: 4 })
      ),
      http.get("/api/v1/policies/default/report-gen/versions", () => HttpResponse.json([])),
      http.get("/api/v1/policies/default/report-gen__remediation__", () =>
        HttpResponse.json({ namespace: "default", agent_class: "report-gen__remediation__", rego_source: "", version: 1 })
      ),
      http.get("/api/v1/policies/default/report-gen__remediation__/versions", () => HttpResponse.json([])),
      // The draft's persistence key (agent_class) is ALREADY the compound overlay key — `affected_class`
      // carries the real class for display.
      http.get("/api/v1/threats/intent-drafts", () =>
        HttpResponse.json({
          drafts: [
            {
              draft_id: "d-rem",
              ns: "default",
              cls: "report-gen__remediation__",
              affected_class: "report-gen",
              enabled: ["deny_pii_exfil"],
              covered_count: 1,
              total: 1,
              created_at: "2026-07-10T12:00:00Z",
              source_framework: "atlas",
              source_control_id: "AML.T0051",
              source_control_name: "LLM Prompt Injection"
            }
          ],
          total: 1,
          returned: 1,
          offset: 0,
          limit: 15
        })
      ),
      http.get("/api/v1/threats/intent-drafts/d-rem", () =>
        HttpResponse.json({
          draft_id: "d-rem",
          ns: "default",
          cls: "report-gen__remediation__",
          affected_class: "report-gen",
          rego: "package norviq.remediation.atlas.aml_t0051\ndefault decision = \"allow\"\n",
          enabled: ["deny_pii_exfil"],
          covered_count: 1,
          total: 1,
          enforcement: "draft",
          source_framework: "atlas",
          source_control_id: "AML.T0051",
          source_control_name: "LLM Prompt Injection"
        })
      )
    );

    let createBody: Record<string, unknown> | null = null;
    server.use(
      http.post("/api/v1/policies", async ({ request }) => {
        createBody = (await request.json()) as Record<string, unknown>;
        return HttpResponse.json({ version: 1 });
      })
    );

    renderPage(["/?intent_draft=d-rem"]);

    // The draft row shows the REAL affected class, never the raw "report-gen__remediation__" persistence key.
    expect(await screen.findByTestId("intent-draft-d-rem")).toHaveTextContent("report-gen");
    expect(screen.queryByText("report-gen__remediation__")).not.toBeInTheDocument();
    // And it is clearly framed as an additive overlay, not a replacement.
    expect(screen.getByTestId("intent-draft-target-d-rem")).toHaveTextContent(/compliance overlay on agent-class report-gen/i);
    expect(screen.getByTestId("intent-draft-target-d-rem")).toHaveTextContent(/never replaces its base policy/i);

    // Also true in the catalog: the base class row is listed separately from the (not-yet-applied) overlay
    // (both render the label "report-gen" — the draft row above, and now the catalog's base-policy card).
    fireEvent.click(screen.getByRole("button", { name: /^catalog$/i }));
    expect(await screen.findByText(/agent-class policies/i)).toBeInTheDocument();
    expect((await screen.findAllByText("report-gen")).length).toBeGreaterThanOrEqual(1);
    expect(screen.queryByText("report-gen__remediation__")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: /^editor$/i }));

    // Review & apply loads the draft's OWN rego into the editor, scoped to the COMPOUND overlay key.
    fireEvent.click(screen.getByRole("button", { name: /review & apply/i }));
    await waitFor(() => expect(screen.getByTestId("monaco-editor")).toHaveTextContent("norviq.remediation.atlas.aml_t0051"));
    // The banner tells the operator this ADDS a block rather than replacing the base policy.
    expect(screen.getByTestId("draft-loaded-banner")).toHaveTextContent(/adds a block/i);
    expect(screen.getByTestId("draft-loaded-banner")).toHaveTextContent("report-gen · compliance overlay");

    // Create persists to the COMPOUND overlay key — never to the base "report-gen" class.
    fireEvent.click(screen.getByTestId("editor-save-policy"));
    await waitFor(() => expect(createBody).toBeTruthy());
    expect(createBody).toMatchObject({ namespace: "default", agent_class: "report-gen__remediation__" });
    expect(createBody!.agent_class).not.toBe("report-gen");
  });

  it("the CURRENT version badge sits on the active (highest) version, not v1", async () => {
    seedHandlers("class");
    server.use(
      http.get("/api/v1/policies/default/customer-support/versions", () =>
        HttpResponse.json(
          [1, 2, 3].map((n) => ({ version: n, saved_by: "attack-suite", saved_at: `2026-07-0${n}T10:00:00Z` }))
        )
      )
    );
    renderPage();
    fireEvent.click(await screen.findByRole("button", { name: /^versions$/i }));
    // The active version is v3 (highest) — CURRENT must be there, NOT on v1.
    const v3row = (await screen.findByText("v3")).closest("tr") as HTMLElement;
    const v1row = screen.getByText("v1").closest("tr") as HTMLElement;
    expect(within(v3row).getByText("current")).toBeInTheDocument();
    expect(within(v1row).queryByText("current")).not.toBeInTheDocument();
  });

  it("clicking a draft row (no deep-link) opens its review with the generated rego", async () => {
    seedHandlers("class");
    server.use(
      http.get("/api/v1/threats/intent-drafts", () =>
        HttpResponse.json({
          drafts: [{ draft_id: "d-1", ns: "default", cls: "billing-agent", enabled: [], covered_count: 3, total: 5, created_at: "2026-07-03T12:00:00Z" }],
          total: 1, returned: 1, offset: 0, limit: 15
        })
      ),
      http.get("/api/v1/threats/intent-drafts/d-1", () =>
        HttpResponse.json({ draft_id: "d-1", ns: "default", cls: "billing-agent", rego: "package norviq.intent.billing\ndefault allow = false\n", enabled: [], covered_count: 3, total: 5, enforcement: "draft" })
      )
    );
    // NO deep-link — start at the plain catalog. Before the fix the row was inert (cursor auto, no handler).
    renderPage(["/"]);
    const row = await screen.findByTestId("intent-draft-open-d-1");
    expect(screen.queryByTestId("intent-draft-rego")).not.toBeInTheDocument(); // closed initially
    fireEvent.click(row);
    // The review opens inline: the generated rego + the coverage are shown.
    expect(await screen.findByTestId("intent-draft-rego")).toHaveTextContent("package norviq.intent.billing");
    expect(screen.getByText(/coverage 3\/5/i)).toBeInTheDocument();
  });

  it("hides the intent-drafts section when there are no drafts (no empty noise)", async () => {
    seedHandlers("class");
    server.use(http.get("/api/v1/threats/intent-drafts", () => HttpResponse.json({ drafts: [], total: 0, returned: 0, offset: 0, limit: 15 })));
    renderPage();
    expect((await screen.findAllByText("customer-support.rego")).length).toBeGreaterThan(0);
    expect(screen.queryByText(/intent drafts · dry-run/i)).not.toBeInTheDocument();
  });

  it("fetches /api/v1/deployments without a 404 (#4)", async () => {
    seedHandlers("class");
    server.use(
      http.get("/api/v1/deployments", ({ request }) => {
        deploymentsCalls += 1;
        if (new URL(request.url).pathname !== "/api/v1/deployments") deployments404 = true;
        return HttpResponse.json([]);
      })
    );
    renderPage();
    await waitFor(() => expect(deploymentsCalls).toBeGreaterThan(0));
    expect(deployments404).toBe(false);
  });

  it("Part A: drafts are grouped by source, status-pilled with target linkage, and test drafts hide by default", async () => {
    localStorage.removeItem("nrvq_show_test_drafts");
    // An enforcing policy for billing-agent (v8) → the draft is a change-to-live (Superseded + linkage).
    server.use(
      http.get("/api/v1/policies", () =>
        HttpResponse.json([{ namespace: "default", agent_class: "billing-agent", current_version: 8, target_type: "class", rego_length: 100, priority: 700 }])
      ),
      http.get("/api/v1/deployments", () => HttpResponse.json([])),
      http.get("/api/v1/policies/default/billing-agent", () =>
        HttpResponse.json({ namespace: "default", agent_class: "billing-agent", rego_source: "package p\n", version: 8 })
      ),
      http.get("/api/v1/policies/default/billing-agent/versions", () => HttpResponse.json([])),
      http.get("/api/v1/threats/intent-drafts", () =>
        HttpResponse.json({
          drafts: [
            { draft_id: "d-comp", ns: "default", cls: "billing-agent", enabled: ["readonly"], covered_count: 0, total: 0, created_at: "2026-07-05T12:00:00Z",
              source_framework: "owasp", source_control_id: "LLM07:2025", source_control_name: "System Prompt Leakage" },
            { draft_id: "d-test", ns: "default", cls: "wave4e2e-probe", enabled: [], covered_count: 0, total: 0, created_at: "2026-07-05T11:00:00Z" }
          ],
          total: 2, returned: 2, offset: 0, limit: 15
        })
      )
    );
    renderPage(["/"]);
    // The compliance draft renders under the "From Compliance gaps" group.
    const group = await screen.findByTestId("draft-group-compliance");
    expect(within(group).getByTestId("intent-draft-d-comp")).toBeInTheDocument();
    // It is SUPERSEDED (an enforcing policy already exists) with the target-linkage version.
    expect(screen.getByTestId("intent-draft-status-d-comp")).toHaveTextContent(/superseded/i);
    expect(screen.getByTestId("intent-draft-target-d-comp")).toHaveTextContent("currently v8 enforcing");
    // The wave4e2e test draft is HIDDEN by default; a toggle reveals it.
    expect(screen.queryByTestId("intent-draft-d-test")).not.toBeInTheDocument();
    const toggle = screen.getByTestId("draft-toggle-test");
    expect(toggle).toHaveTextContent(/1 test draft hidden — Show/i);
    fireEvent.click(toggle);
    expect(await screen.findByTestId("intent-draft-d-test")).toBeInTheDocument();
    // A per-draft dismiss control exists.
    expect(screen.getByTestId("intent-draft-dismiss-d-comp")).toBeInTheDocument();
  });
});

describe("PolicyCatalog — create (raw rego) / delete (guardrails)", () => {
  it("New policy authors raw rego for a chosen ns+class and creates via POST /policies", async () => {
    seedHandlers("class");
    let createBody: Record<string, unknown> | null = null;
    server.use(
      http.post("/api/v1/policies", async ({ request }) => {
        createBody = (await request.json()) as Record<string, unknown>;
        return HttpResponse.json({ version: 1 });
      })
    );
    renderPage();
    // Enter raw-rego new-policy mode from the editor rail.
    fireEvent.click(await screen.findByTestId("editor-new-policy"));
    // The scope selector (ns + class + mode) appears and Monaco carries the editable starter rego.
    expect(await screen.findByTestId("new-policy-fields")).toBeInTheDocument();
    expect(screen.getByTestId("monaco-editor")).toHaveTextContent("custom_block_rule");
    // Type a fresh ns + class, then Create.
    fireEvent.change(screen.getByTestId("new-policy-namespace"), { target: { value: "sandbox" } });
    fireEvent.change(screen.getByTestId("new-policy-class"), { target: { value: "finance-agent" } });
    fireEvent.click(screen.getByTestId("editor-save-policy"));
    await waitFor(() => expect(createBody).toBeTruthy());
    expect(createBody).toMatchObject({ namespace: "sandbox", agent_class: "finance-agent", enforcement_mode: "block" });
    expect(String(createBody!.rego_source)).toContain("custom_block_rule");
  });

  it("Create is disabled until a non-reserved class is entered", async () => {
    seedHandlers("class");
    renderPage();
    fireEvent.click(await screen.findByTestId("editor-new-policy"));
    const save = await screen.findByTestId("editor-save-policy");
    expect(save).toBeDisabled(); // empty class
    fireEvent.change(screen.getByTestId("new-policy-class"), { target: { value: "__baseline__" } });
    expect(save).toBeDisabled(); // reserved scope
    expect(screen.getByTestId("new-policy-reserved-warn")).toBeInTheDocument();
    fireEvent.change(screen.getByTestId("new-policy-class"), { target: { value: "ok-agent" } });
    expect(save).not.toBeDisabled();
  });

  it("editor Delete confirms ns+class+version + enforcing warning, then DELETEs that scope", async () => {
    seedHandlers("class");
    let deletePath = "";
    server.use(
      http.delete("/api/v1/policies/:ns/:cls", ({ params }) => {
        deletePath = `${params.ns}/${params.cls}`;
        return HttpResponse.json({ deleted: true });
      })
    );
    renderPage();
    fireEvent.click(await screen.findByTestId("editor-delete-policy"));
    const modal = await screen.findByTestId("delete-policy-modal");
    expect(modal).toHaveTextContent("default/customer-support");
    expect(modal).toHaveTextContent("v1");
    expect(screen.getByTestId("delete-policy-warning")).toHaveTextContent(/currently enforcing/i);
    fireEvent.click(screen.getByTestId("delete-policy-confirm"));
    await waitFor(() => expect(deletePath).toBe("default/customer-support"));
  });

  it("cancelling the delete confirm fires NO DELETE", async () => {
    seedHandlers("class");
    let deleteCalled = false;
    server.use(
      http.delete("/api/v1/policies/:ns/:cls", () => {
        deleteCalled = true;
        return HttpResponse.json({ deleted: true });
      })
    );
    renderPage();
    fireEvent.click(await screen.findByTestId("editor-delete-policy"));
    await screen.findByTestId("delete-policy-modal");
    fireEvent.click(screen.getByRole("button", { name: /^cancel$/i }));
    await waitFor(() => expect(screen.queryByTestId("delete-policy-modal")).not.toBeInTheDocument());
    expect(deleteCalled).toBe(false);
  });

  it("reserved scopes (__baseline__) show NO delete affordance in the catalog", async () => {
    server.use(
      http.get("/api/v1/policies", () =>
        HttpResponse.json([
          { namespace: "default", agent_class: "__baseline__", current_version: 1, rego_length: 50, priority: 700, target_type: "class" },
          { namespace: "default", agent_class: "finance-agent", current_version: 2, rego_length: 80, priority: 100, target_type: "class" }
        ])
      ),
      http.get("/api/v1/deployments", () => HttpResponse.json([])),
      http.get("/api/v1/policies/default/:cls", () => HttpResponse.json({ rego_source: "package x\n", version: 1 })),
      http.get("/api/v1/policies/default/:cls/versions", () => HttpResponse.json([]))
    );
    renderPage();
    fireEvent.click(await screen.findByRole("button", { name: /^catalog$/i }));
    // The normal class has a delete affordance; the reserved __baseline__ does not.
    expect(await screen.findByTestId("catalog-delete-finance-agent")).toBeInTheDocument();
    expect(screen.queryByTestId("catalog-delete-__baseline__")).not.toBeInTheDocument();
  });

  // FIX A: an EXISTING (already-saved) policy's mode was read-only in the editor — no <select> with an
  // onChange existed outside the `newPolicy` (create) case, so "Save" could never submit a changed mode and
  // the editor's "Enforcement -> audit" change was silently dropped.
  it("FIX A: changing Enforcement on an EXISTING loaded policy marks it unsaved and Save submits the new mode", async () => {
    seedHandlers("class");
    let saveBody: Record<string, unknown> | null = null;
    server.use(
      http.post("/api/v1/policies", async ({ request }) => {
        saveBody = (await request.json()) as Record<string, unknown>;
        return HttpResponse.json({ version: 2 });
      })
    );
    renderPage();
    await screen.findAllByText("customer-support.rego");

    const modeSelect = await screen.findByTestId("editor-existing-mode");
    expect(modeSelect).toHaveValue("block"); // default when the list response carries no mode

    fireEvent.change(modeSelect, { target: { value: "audit" } });
    expect(await screen.findByText(/unsaved changes/i)).toBeInTheDocument();

    fireEvent.click(screen.getByTestId("editor-save-policy"));
    await waitFor(() => expect(saveBody).toBeTruthy());
    expect(saveBody).toMatchObject({
      namespace: "default",
      agent_class: "customer-support",
      enforcement_mode: "audit"
    });
  });

  // saveEditorPolicy only called setApplyResult inside the `newPolicy` (create) branch — the
  // existing-policy Save path (this is exactly Bug #2's own repro: editor Enforcement -> audit) only showed
  // the small "Saved ✓" badge, with no verify-poll giving Bug #4-style convergence feedback.
  it("saving an EXISTING loaded policy also shows the apply-result panel + verify-poll, not just 'Saved'", async () => {
    seedHandlers("class");
    server.use(
      http.post("/api/v1/policies", async () => HttpResponse.json({ version: 2 }))
    );
    renderPage();
    await screen.findAllByText("customer-support.rego");

    const modeSelect = await screen.findByTestId("editor-existing-mode");
    fireEvent.change(modeSelect, { target: { value: "audit" } });
    await screen.findByText(/unsaved changes/i);

    fireEvent.click(screen.getByTestId("editor-save-policy"));

    // The small inline badge still shows...
    expect(await screen.findByText(/Saved ✓/)).toBeInTheDocument();
    // ...AND the ApplyResultPanel now renders for the existing-policy path too, with its verify-poll
    // (expectedVersion set -> localVerifying -> "Verifying — confirming the new version is loaded…").
    expect(await screen.findByText(/Saved default\/customer-support/)).toBeInTheDocument();
    expect(await screen.findByText(/Verifying — confirming the new version is loaded/i)).toBeInTheDocument();
  });
});
