apiVersion: v1
kind: Service
metadata:
  name: norviq-api
  namespace: {{ .Values.namespace }}
  labels:
    app: norviq-api
    {{- include "norviq.labels" . | nindent 4 }}
spec:
  selector:
    app: norviq-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
