apiVersion: v1
kind: ServiceAccount
metadata:
  name: norviq-controller
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: norviq-controller
rules:
  - apiGroups: ["norviq.io"]
    resources: ["nrvqpolicies", "nrvqpolicies/status", "nrvqclasses", "nrvqclasses/status", "nrvqconfigs", "nrvqconfigs/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: norviq-controller
subjects:
  - kind: ServiceAccount
    name: norviq-controller
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: norviq-controller
  apiGroup: rbac.authorization.k8s.io
