{{- if and .Values.postgresql.enabled (not .Values.postgresql.ha.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: norviq-postgresql-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: norviq-postgresql
    {{- include "norviq.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
{{- end }}
