{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: norviq-postgresql-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: norviq-postgresql
    {{- include "norviq.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
{{- end }}
