{{- if and .Values.redis.enabled (not .Values.redis.ha.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: norviq-redis-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: norviq-redis
    {{- include "norviq.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
{{- end }}
