{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: norviq-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: norviq-redis
    {{- include "norviq.componentLabels" (dict "root" $ "component" "redis") | nindent 4 }}
spec:
  selector:
    app: norviq-redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      name: redis
  clusterIP: None
{{- end }}
