apiVersion: v1
kind: Secret
metadata:
  name: norviq-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "norviq.labels" . | nindent 4 }}
type: Opaque
stringData:
  NRVQ_API_SECRET_KEY: {{ .Values.api.secretKey | quote }}
  {{- $redisHost := ternary .Values.redis.ha.serviceName "norviq-redis" .Values.redis.ha.enabled }}
  {{- $pgHost := ternary .Values.postgresql.ha.serviceName "norviq-postgresql" .Values.postgresql.ha.enabled }}
  NRVQ_REDIS_URL: "redis://:{{ .Values.redis.password }}@{{ $redisHost }}:{{ .Values.redis.port }}"
  NRVQ_PG_URL: "postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ $pgHost }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
