{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: norviq-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: norviq-webhook
    {{- include "norviq.labels" . | nindent 4 }}
spec:
  selector:
    app: norviq-webhook
  ports:
    - name: https
      port: 443
      targetPort: https
{{- end }}
