# SPDX-License-Identifier: Apache-2.0
images:
  engine:
    tag: engine-latest
    pullPolicy: Always
  api:
    tag: api-latest
    pullPolicy: Always
  ui:
    tag: ui-latest
    pullPolicy: Always

api:
  secretKey: "dev-secret-key"

redis:
  password: "dev-redis-password"

postgresql:
  password: "dev-pg-password"
  storage: 1Gi

config:
  logLevel: DEBUG
  enforcementMode: audit
